POST http://localhost:8080/player
Content-Type: application/json

{
    "pseudo": "henri"
}

### Successful test: check response status is 200
GET http://localhost:8080/player
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###

GET http://localhost:8080/player/
Accept: application/json
###

GET http://localhost:8080/player/pierre
Accept: application/json

###
PUT http://localhost:8080/player
Content-Type: application/json

{
    "pseudo": "henri"
}
###

DELETE http://localhost:8080/player
Accept: application/json